# The first X gives out the output "3" 
# The second X example gives an error message because the "x" variable is only defined inside the scope of the block and it is being called
# outside of the block in the example.